apiVersion: batch/v1
kind: Job
metadata:
  name: geode-perf-test-get
spec:
  template:
    spec:
      containers:
        - name: apache-geode-perf-test-get
          image: cloudnativedata/apache-geode-perf-test:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: "JVM_ARGS"
              value: "-Xms4g -Xmx4g -XX:+UseG1GC -XX:+PrintGCDetails -XX:MaxGCPauseMillis=10"
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: action
              value: "get"
            - name: loopCount
              value: "10000"
            - name: capacity
              value: "8000"
            - name: regionName
              value: "test"
      restartPolicy: Never
  backoffLimit: 4
