apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: cluster-b
  namespace: default
spec:
  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:9.15.0
  security:
    tls: {}
  antiAffinityPolicy: None
  metrics:
    emission: Default
  locators:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
    overrides:
      gemFireProperties:
        - name: "distributed-system-id"
          value: "2"
        - name: "remote-locators"
          value: "cluster-a-locator-0.cluster-a-locator.default.svc.cluster.local[10334]"
  servers:
    replicas: 1
    resources:
      requests:
        memory: 1Gi