apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire2
spec:
  image:  registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:9.15.0
  locators:
    replicas: 2
    overrides:
      gemFireProperties:
        - name: "distributed-system-id"
          value: "2"
        - name: "remote-locators"
          value: "gemfire1-locator-0.gemfire1-locator.default.svc.cluster.local[10334],gemfire1-locator-1.gemfire1-locator.default.svc.cluster.local[10334]"
  servers:
    replicas: 3
    overrides:
      jvmOptions:
        - "-Xms674m"
        - "-Xmx674m"
        - "-Dgemfire.statistic-sample-rate=5000"
        - "-Dgemfire.enable-time-statistics=true"
        - "-Dgemfire.statistic-sampling-enabled=true"
        - "-Dgemfire.standard-output-always-on=true"
        - "-Dgemfire.archive-file-size-limit=10"
        - "-Dgemfire.conserve-sockets=false"
        - "-Dgemfire.prometheus.metrics.port=4321"
        - "-Dgemfire.log-disk-space-limit=409"
        - "-Dgemfire.archive-disk-space-limit=409"
        - "-Dgemfire.log-file-size-limit=100"
        - "-Dgemfire.locator-wait-time=120"
        - "-Dgemfire.ALLOW_PERSISTENT_TRANSACTIONS=true"
      gemFireProperties:
        - name: "distributed-system-id"
          value: "2"
        - name: "remote-locators"
          value: "gemfire1-locator-0.gemfire1-locator.default.svc.cluster.local[10334],gemfire1-locator-1.gemfire1-locator.default.svc.cluster.local[10334]"