apiVersion: batch/v1
kind: Job
metadata:
  name: geode-perf-test-put-02
spec:
  template:
    spec:
      containers:
        - name: apache-geode-perf-test-put-01
          image: cloudnativedata/apache-geode-perf-test:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: "JVM_ARGS"
              value: "-Xms4g -Xmx4g -XX:+UseG1GC -XX:+PrintGCDetails -XX:MaxGCPauseMillis=10"
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: action
              value: "putStringThroughput"
            - name: threadCount
              value: "10"
            - name: threadSleepMs
              value: "0"
            - name: loopCount
              value: "9000000"
            - name: capacity
              value: "8000"
            - name: regionName
              value: "test"
            - name: maxCountPerThread
              value: "90000"
            - name: valueLength
              value: "32"
            - name: keyPrefix
              value: "T2-1"
        - name: apache-geode-perf-test-put-02
          image: cloudnativedata/apache-geode-perf-test:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: "JVM_ARGS"
              value: "-Xms4g -Xmx4g -XX:+UseG1GC -XX:+PrintGCDetails -XX:MaxGCPauseMillis=10"
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: action
              value: "putStringThroughput"
            - name: threadCount
              value: "10"
            - name: threadSleepMs
              value: "0"
            - name: loopCount
              value: "9000000"
            - name: capacity
              value: "8000"
            - name: regionName
              value: "test"
            - name: maxCountPerThread
              value: "90000"
            - name: valueLength
              value: "32"
            - name: keyPrefix
              value: "T2-2"
        - name: apache-geode-perf-test-put-03
          image: cloudnativedata/apache-geode-perf-test:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: "JVM_ARGS"
              value: "-Xms4g -Xmx4g -XX:+UseG1GC -XX:+PrintGCDetails -XX:MaxGCPauseMillis=10"
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: action
              value: "putStringThroughput"
            - name: threadCount
              value: "10"
            - name: threadSleepMs
              value: "0"
            - name: loopCount
              value: "9000000"
            - name: capacity
              value: "8000"
            - name: regionName
              value: "test"
            - name: maxCountPerThread
              value: "90000"
            - name: valueLength
              value: "32"
            - name: keyPrefix
              value: "T2-3"
        - name: apache-geode-perf-test-put-04
          image: cloudnativedata/apache-geode-perf-test:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: "JVM_ARGS"
              value: "-Xms4g -Xmx4g -XX:+UseG1GC -XX:+PrintGCDetails -XX:MaxGCPauseMillis=10"
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: action
              value: "putStringThroughput"
            - name: threadCount
              value: "10"
            - name: threadSleepMs
              value: "0"
            - name: loopCount
              value: "9000000"
            - name: capacity
              value: "8000"
            - name: regionName
              value: "test"
            - name: maxCountPerThread
              value: "90000"
            - name: valueLength
              value: "32"
            - name: keyPrefix
              value: "T2-4"
        - name: apache-geode-perf-test-put-05
          image: cloudnativedata/apache-geode-perf-test:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          env:
            - name: "JVM_ARGS"
              value: "-Xms4g -Xmx4g -XX:+UseG1GC -XX:+PrintGCDetails -XX:MaxGCPauseMillis=10"
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
            - name: action
              value: "putStringThroughput"
            - name: threadCount
              value: "10"
            - name: threadSleepMs
              value: "0"
            - name: loopCount
              value: "9000000"
            - name: capacity
              value: "8000"
            - name: regionName
              value: "test"
            - name: maxCountPerThread
              value: "90000"
            - name: valueLength
              value: "32"
            - name: keyPrefix
              value: "T2-5"
      restartPolicy: Never
  backoffLimit: 4
